---
title: "STATG019 ICA2 Part A"
author: "Student Number: 16035918, 16044460, 17107203"
header-includes:
   - \usepackage{amsmath, amsfonts, nicefrac, bm, fancyhdr}
   - \newcommand{\matr}[1]{\bm{\mathrm{#1}}}
   - \pagestyle{fancy}
   - \fancyhf{}
   - \rhead{16035918, 16044460, 17107203}
   - \rfoot{Page \thepage}
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = FALSE, cache = TRUE, cache.lazy = FALSE)
```

# Data Transformation and Exploration
## Setup

```{r load_pkgs, message=FALSE, warning=FALSE}

# use pacman for package management
if(!require("pacman")) {
    install.packages("pacman")
}

# load the tidyverse, joyplots (now in ggridges) for plots,
# magrittr for pipes, summarytools for descriptives
pacman::p_load(
  tidyverse, ggridges, magrittr, summarytools, GGally, mclust, feather)
# load the ML libraries needed for benchmarking
pacman::p_load(mlr, kernlab, h2o)

```

```{r load_data, message=FALSE}

# read in the csv files
wine <- 
  bind_rows(
    # read in white, encode as 0
    read_delim('./input/winequality-white.csv', delim=';', guess_max=10000) %>%
      mutate(color=0L),
    # read in red, encode as 1
    read_delim('./input/winequality-red.csv', delim=';', guess_max=10000) %>%
      mutate(color=1L)
  )

# check the result
dim(wine)
str(wine)
head(wine)
summary(wine)
```


```{r helper-functions}
recode_color_ <- function(x) dplyr::recode(x, `1` = 'Red', `0` = 'White')
recode_color <- function(x){
  # used to avoid factors, which can be capricious
  
  switch(
    is.data.frame(x) + 1,
    # if not a dataframe, directly recode
    recode_color_(x),
    # if a dataframe, overwrite color column (presumed to exist)
    dplyr::mutate(x, color=recode_color_(color))
  )
}
```

## Exploration
### Summary Statistics

```{r summary-stats}
q025 <- function(x) quantile(x, 0.25)
q075 <- function(x) quantile(x, 0.75)

wine_summary <-
  wine %>%
  
  # summary statistics by color
  # perhaps a little cleaner to look overall?
  group_by(color) %>%
  summarize_all(
    funs(min, q025, median,  mean, q075, max, sd)
  ) %>%
  
  # transform data
  gather(... = -color) %>%
  separate(key, into = c('Variable', 'statistic'), sep = '_') %>%
  spread(key = statistic, value = value)

# order variables with highest variation (after rescaling)
variable_var <-
  wine %>%
  select(-quality, -color) %>%
  # min-max scale the data
  mutate_all(funs(. / (max(.) - min(.)))) %>%
  # take variances
  summarize_all(var) %>%
  # reshape and sort
  gather %>%
  arrange(-value)

# make beautiful
wine_summary %>%
  recode_color %>%
  select(
    Color=color, 
    Variable,
    Min = min,
    `1st Quantile` = q025,
    Median = median,
    Mean = mean,
    `3rd Quantile` = q075,
    Max = max,
    `S.D.`=sd
  ) %>%
  arrange(Variable) %>%
  knitr::kable(format='latex')
```

### Histograms

```{r histograms}
# plot histograms (unscaled)
wine %>%
  select(-color) %>%
  #mutate_at(vars(-alcohol, -pH, -quality), log) %>%
  gather(key='Variable', value='Value') %>%
  ggplot(aes(x = Value)) +
  geom_histogram(bins = 50) +
  facet_wrap(~Variable, scale='free') +
  ggtitle('Variable Histograms')
```

### Pairs Plots of Variables

```{r pairs-plot, message=FALSE}
# pairs plot of the n variables with the greatest variance
n <- 5
wine %>%
  recode_color %>%
  ggpairs(
    mapping=aes(color=color, alpha=0.4),
    columns=variable_var$key[1:n]
  )
```

### Variable correlations

```{r cor-heatmap, fig.height=6, fig.width=6}
wine_cor <-
  wine %>%
  select(-quality, -color) %>%
  mutate_all(log1p) %>%
  # get correlations
  cor

wine_cor[upper.tri(wine_cor, diag = TRUE)] <- NA
  
wine_cor %>%
  reshape2::melt() %>%
  # plot
  ggplot(aes(x=Var1, y=Var2, fill=value)) +
  geom_tile() +
  scale_fill_gradient2(name = 'Pearson Corr.',
                       limit=c(-1, 1)) + 
  # geom_text(aes(label=round(value, 2))) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  coord_fixed()
  
```

## Data Transformation

```{r variable_transformations}
# Do we need to convert the concentrations that are mg/dm3 compared to those that are g/dm3?

# convert all concentration variables to the log scale
origwine <- wine

concvars <- c(
  "fixed acidity",
  "volatile acidity",
  "citric acid",
  "residual sugar",
  "chlorides",
  "free sulfur dioxide",
  "total sulfur dioxide",
  "sulphates"
)

wine <- 
    origwine %>% 
    mutate_at(.vars = vars(concvars),
              .funs = log1p) %>% 
    # scale the data (can turn off later)
    mutate_at(vars(-color, -quality), funs(scale(.) %>% as.numeric))
```

### Exploration of Data and Transformed Data

```{r explore}

# get some summaries of the transformed data
summarytools::dfSummary(wine)
# some data still looks pretty skewed, even after a log transform and standardising

# distribution of wine quality as a factor
summarytools::freq(wine$quality)

# distribution of wine quality by color
with(recode_color(wine), summarytools::ctable(color, quality))

# descriptive statistics for all variables - untransformed
summarytools::descr(origwine, transpose = T)

# descriptive statistics for all variables - transformed
summarytools::descr(wine, transpose = T)

# descriptive statistics by wine color (using untransformed data)
origwine_stats_by_color <- by(data = recode_color(origwine), 
                           INDICES = origwine$color, 
                           FUN = descr, stats = c("mean", "sd", "min", "med", "max"), transpose = TRUE)
view(origwine_stats_by_color, method = "pander")

# descriptive statistics by wine color (using transformed data)
wine_stats_by_color <- by(data = recode_color(wine), 
                           INDICES = wine$color, 
                           FUN = descr, stats = c("mean", "sd", "min", "med", "max"), transpose = TRUE)
view(wine_stats_by_color, method = "pander")
```

### Ridge plots

```{r plots}
# ridge plot function

ridgeplot <- function(winevar) {
    
    origwine %>%
        recode_color %>%
        ggplot(aes(y = quality)) +
        geom_density_ridges(aes_q(x = as.name(winevar),
                                  fill = paste(origwine$quality, origwine$color)), 
                            alpha = .8,
                            color = "white",
                            rel_min_height = 0.01) +
        labs(x = Hmisc::capitalize(gsub(x = winevar,
                                            pattern = "\\.",
                                            replacement = " ")),
             y = "Wine quality") +
        scale_y_discrete(expand = c(0.01, 0)) +
        scale_x_continuous(expand = c(0.01, 0)) +
        scale_fill_cyclical(breaks = c("3 White", "3 Red"),
                            labels = c(`3 White` = "White", `3 Red` = "Red"),
                            values = c("#E31A1C", "#33A02C", "#FB9A99", "#B2DF8A"),
                            name = "Wine color", guide = "legend") +
        theme_ridges(grid = FALSE, font_size = 11)
}

ridgeplotlist <- lapply(names(origwine)[1:11], ridgeplot)
ridgeplots_grid <- ggpubr::ggarrange(plotlist = ridgeplotlist, ncol = 2, nrow = 2)
ridgeplots_grid
# write plots to PDF
#if(!file.exists("winevars_ridgeplots.pdf")){
#    ggpubr::ggexport(ridgeplots_grid, filename = "winevars_ridgeplots.pdf")
#}
```
## Clustering

```{r kmeans}
## do clusgap (takes a while)
## also look at mclust/hclust
## look at pairs plot
## look at sulfates v quality, clusters v sulfates, quality v clusters
## scale as well
## consider looking at ARI/ASW

mclust_results <-
  select(wine, -quality, -color) %>%
  Mclust(1:15)
```

```{r plot-clustering}
wine$cluster <- factor(mclust_results$classification)

# do we observe clearly-delineated clusters?
wine %>%
  ggpairs(
      mapping = aes(color = cluster, alpha = 0.4),
      columns = c(variable_var$key[1:n])
  )
  
# do they divide up quality in any meaningful way?
# not especially! perhaps this isn't the most salient feature
wine %>%
  ggplot(aes(x = quality)) +
  geom_bar(aes(fill = cluster))
  
# also examine relationship to color
wine %>%
  recode_color %>%
  ggplot(aes(x = color)) +
  geom_bar(aes(fill = cluster))

# remove cluster variable
wine$cluster <- NULL
```

# Training Learners
## Save data
```{r save-data, eval=FALSE, include=FALSE}
# save the data in binary format for python interoperability
write_feather(wine, './intermediate/wine_logged_scaled.feather')
origwine %>%
  mutate_at(.vars = vars(concvars),
            .funs = log1p) %>%
  write_feather('./intermediate/wine_logged_unscaled.feather')
```

```{python, engine.path='C:/Miniconda3/envs/py36/python.exe'}
# for now, included in learners.py
```